# f1 = open("demo3.txt","r+")
# # print(f1.tell()) # tells us where the file pointer is located
# # print(f1.readline())
# # print(f1.tell())
# # print(f1.readline())
# print(f1.readline())
# print(f1.seek(3))
# print(f1.tell())
# print(f1.readline())
# #print(f1.write("No"))
# f1.close()
with open("demo3.txt") as f: # if we use with open("demo3.txt")(it closes by itself) as f: we donot have to use f.close()
    a = f.readlines()
    print(a)
f = open("demo3.txt", "rt")
print(f.read())
f.close()